# Generated by Django 3.1.7 on 2021-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210227_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Initial', max_length=50),
            preserve_default=False,
        ),
    ]
