# Generated by Django 3.1.7 on 2021-02-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'News'},
        ),
    ]
