# Generated by Django 3.1.7 on 2021-02-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210228_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='owner',
        ),
    ]
